name: Build and image push using
on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
        - name: Checkout Code
          uses: actions/checkout@v3

        - name: Log in to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GH_PAT }}

        - name: Build Docker Image
          run: |
            IMAGE_NAME=ghcr.io/${{ github.repository }}
            IMAGE_TAG=${{ github.sha }}
            docker build -t $IMAGE_NAME:IMAGE_TAG .

        - name: Push Docker Image
          run: |
            IMAGE_NAME=ghcr.io/${{ github.repository }}
            IMAGE_TAG=${{ github.sha }}
            docker push $IMAGE_NAME:IMAGE_TAG